/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVideoInfoRouteImport } from './routes/api/video-info'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoInfoRoute = ApiVideoInfoRouteImport.update({
  id: '/api/video-info',
  path: '/api/video-info',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/video-info': typeof ApiVideoInfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/video-info': typeof ApiVideoInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/video-info': typeof ApiVideoInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/video-info'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/video-info'
  id: '__root__' | '/' | '/api/video-info'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiVideoInfoRoute: typeof ApiVideoInfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-info': {
      id: '/api/video-info'
      path: '/api/video-info'
      fullPath: '/api/video-info'
      preLoaderRoute: typeof ApiVideoInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiVideoInfoRoute: ApiVideoInfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
